//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bancho_client_hardware_records")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i32,
    pub time_offset: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub path_hash: String,
    pub adapters: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub adapters_hash: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub uninstall_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub disk_id: String,
    pub used_times: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
