//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "game_mode")]
pub enum GameMode {
    #[sea_orm(string_value = "Fruits")]
    Fruits,
    #[sea_orm(string_value = "Mania")]
    Mania,
    #[sea_orm(string_value = "Standard")]
    Standard,
    #[sea_orm(string_value = "Taiko")]
    Taiko,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "performance_version"
)]
pub enum PerformanceVersion {
    #[sea_orm(string_value = "v1")]
    V1,
    #[sea_orm(string_value = "v2")]
    V2,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "rank_status")]
pub enum RankStatus {
    #[sea_orm(string_value = "Approved")]
    Approved,
    #[sea_orm(string_value = "Graveyard")]
    Graveyard,
    #[sea_orm(string_value = "Loved")]
    Loved,
    #[sea_orm(string_value = "Pending")]
    Pending,
    #[sea_orm(string_value = "Qualified")]
    Qualified,
    #[sea_orm(string_value = "Ranked")]
    Ranked,
    #[sea_orm(string_value = "Wip")]
    Wip,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ranking_type")]
pub enum RankingType {
    #[sea_orm(string_value = "performance_v1")]
    PerformanceV1,
    #[sea_orm(string_value = "performance_v2")]
    PerformanceV2,
    #[sea_orm(string_value = "score_v1")]
    ScoreV1,
    #[sea_orm(string_value = "score_v2")]
    ScoreV2,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "score_grade")]
pub enum ScoreGrade {
    #[sea_orm(string_value = "A")]
    A,
    #[sea_orm(string_value = "B")]
    B,
    #[sea_orm(string_value = "C")]
    C,
    #[sea_orm(string_value = "D")]
    D,
    #[sea_orm(string_value = "F")]
    F,
    #[sea_orm(string_value = "S")]
    S,
    #[sea_orm(string_value = "SH")]
    Sh,
    #[sea_orm(string_value = "X")]
    X,
    #[sea_orm(string_value = "XH")]
    Xh,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "score_status")]
pub enum ScoreStatus {
    #[sea_orm(string_value = "Failed")]
    Failed,
    #[sea_orm(string_value = "High")]
    High,
    #[sea_orm(string_value = "Passed")]
    Passed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "score_version")]
pub enum ScoreVersion {
    #[sea_orm(string_value = "v1")]
    V1,
    #[sea_orm(string_value = "v2")]
    V2,
}
