//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "game_mode")]
pub enum GameMode {
    #[sea_orm(string_value = "Fruits")]
    Fruits,
    #[sea_orm(string_value = "Mania")]
    Mania,
    #[sea_orm(string_value = "Standard")]
    Standard,
    #[sea_orm(string_value = "Taiko")]
    Taiko,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "rank_status")]
pub enum RankStatus {
    #[sea_orm(string_value = "Approved")]
    Approved,
    #[sea_orm(string_value = "Graveyard")]
    Graveyard,
    #[sea_orm(string_value = "Loved")]
    Loved,
    #[sea_orm(string_value = "Pending")]
    Pending,
    #[sea_orm(string_value = "Qualified")]
    Qualified,
    #[sea_orm(string_value = "Ranked")]
    Ranked,
    #[sea_orm(string_value = "Wip")]
    Wip,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "score_grade")]
pub enum ScoreGrade {
    #[sea_orm(string_value = "A")]
    A,
    #[sea_orm(string_value = "B")]
    B,
    #[sea_orm(string_value = "C")]
    C,
    #[sea_orm(string_value = "D")]
    D,
    #[sea_orm(string_value = "F")]
    F,
    #[sea_orm(string_value = "S")]
    S,
    #[sea_orm(string_value = "SH")]
    Sh,
    #[sea_orm(string_value = "X")]
    X,
    #[sea_orm(string_value = "XH")]
    Xh,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "score_status")]
pub enum ScoreStatus {
    #[sea_orm(string_value = "Failed")]
    Failed,
    #[sea_orm(string_value = "High")]
    High,
    #[sea_orm(string_value = "Passed")]
    Passed,
}
